core/cart/urls.py
from django.urls import path
from . import views

app_name = "cart"

urlpatterns = [
    path('session/add-product/', views.SessionAddProductView.as_view(),
         name='session-add-product'),
    path('session/remove-product/', views.SessionRemoveProductView.as_view(),
         name='session-remove-product'),
    path('session/update-product-quantity/', views.SessionUpdateProductQuantityView.as_view(),
         name='session-update-product-quantity'),
    path('summary/', views.CartSummaryView.as_view(),
         name='cart-summary'),
]

core/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
    path('', include('website.urls')),
    path('accounts/', include('accounts.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('shop/', include('shop.urls')),
    path('cart/', include('cart.urls')),
    path('order/', include('order.urls')),
    path('payment/', include('payment.urls')),
    path('review/', include('review.urls')),
]


if settings.SHOW_DEBUGGER_TOOLBAR:
    urlpatterns += [path('__debug__/', include('debug_toolbar.urls')),
                    ]


if settings.DEBUG:
    # add root static files
    urlpatterns = urlpatterns + \
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    # add media static files
    urlpatterns = urlpatterns + \
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/shop/urls.py
from django.urls import path, re_path
from . import views

app_name = "shop"

urlpatterns = [
    path("product/grid/", views.ProductGridView.as_view(), name="product-grid"),
    re_path(r"product/(?P<slug>[^/]+)/",
            views.ProductDetailView.as_view(), name="product-detail"),
    path('add-or-remove-wishlist/', views.AddOrRemoveWishlistView.as_view(),
         name='add-or-remove-wishlist'),
]

core/shop/models.py
from django.conf import settings
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.utils.translation import gettext_lazy as _
from decimal import Decimal
from tinymce.models import HTMLField


class StatusType(models.IntegerChoices):
    draft = 1, _("draft")
    publish = 2, _("publish")


class ProductCategory(models.Model):
    title = models.CharField(max_length=255)
    slug = models.SlugField(allow_unicode=True)
    image = models.ImageField(upload_to="product/category/")
    description = HTMLField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return self.title


class Product(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.PROTECT)
    category = models.ManyToManyField(ProductCategory, related_name="category")
    title = models.CharField(max_length=255)
    slug = models.SlugField(allow_unicode=True)
    image = models.ImageField(upload_to="product/img")
    description = HTMLField()
    short_description = HTMLField(null=True, blank=True)
    stock = models.PositiveIntegerField(default=0)
    status = models.IntegerField(
        choices=StatusType.choices, default=StatusType.draft.value)
    sku = models.CharField(unique=True)
    price = models.DecimalField(default=0, max_digits=15, decimal_places=0)
    discount_percent = models.IntegerField(
        default=0, validators=[MinValueValidator(0), MaxValueValidator(100)])
    avg_rate = models.FloatField(default=0.0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return self.title

    def get_price(self):
        discount_amount = self.price * Decimal(self.discount_percent / 100)
        discounted_amount = self.price - discount_amount
        return round(discounted_amount)

    class Meta:
        ordering = ["-created_at"]


class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="product/img")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)


class WishlistProducts(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)

    def __str__(self):
        return self.product.title

core/dashboard/admin/forms/products.py
from django import forms
from django.utils.translation import gettext_lazy as _
from shop.models import Product


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = [
            "title",
            "slug",
            "category",
            "image",
            "description",
            "short_description",
            "stock",
            "status",
            "sku",
            "price",
            "discount_percent",
        ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['title'].widget.attrs['class'] = "form-control"
        self.fields['slug'].widget.attrs['class'] = "form-control"
        self.fields['category'].widget.attrs['class'] = "form-select"
        self.fields['image'].widget.attrs['class'] = "form-control"
        self.fields['description'].widget.attrs['class'] = "form-control"
        self.fields['short_description'].widget.attrs['class'] = "form-control"
        self.fields['stock'].widget.attrs['class'] = "form-control"
        self.fields['stock'].widget.attrs['type'] = "number"
        self.fields['status'].widget.attrs['class'] = "form-select"
        self.fields['sku'].widget.attrs['class'] = "form-control"
        self.fields['price'].widget.attrs['class'] = "form-control"
        self.fields['discount_percent'].widget.attrs['class'] = "form-control"
        self.fields['discount_percent'].widget.attrs['type'] = "number"

core/dashboard/admin/views/products.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import UpdateView, ListView, DeleteView, CreateView
from dashboard.admin.forms import ProductForm
from dashboard.permissions import HasAdminAccessPermission
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import redirect
from shop.models import Product, ProductCategory
from django.core import exceptions
from django.utils.translation import gettext_lazy as _


class AdminProductListView(LoginRequiredMixin, HasAdminAccessPermission, ListView):
    template_name = "dashboard/admin/products/product-list.html"
    paginate_by = 10

    def get_paginate_by(self, queryset):

        return self.request.GET.get('page_size', self.paginate_by)

    def get_queryset(self):
        queryset = Product.objects.all()
        if search_q := self.request.GET.get("q"):
            queryset = queryset.filter(title__icontains=search_q)
        if category_id := self.request.GET.get("category_id"):
            queryset = queryset.filter(category__id=category_id)
        if min_price := self.request.GET.get("min_price"):
            queryset = queryset.filter(price__gte=min_price)
        if max_price := self.request.GET.get("max_price"):
            queryset = queryset.filter(price__lte=max_price)
        if order_by := self.request.GET.get("order_by"):
            try:
                queryset = queryset.order_by(order_by)
            except exceptions.FieldError:
                pass
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['total_items'] = self.get_queryset().count()
        context['categories'] = ProductCategory.objects.all()
        return context


class AdminProductCreateView(LoginRequiredMixin, HasAdminAccessPermission, SuccessMessageMixin, CreateView):
    template_name = "dashboard/admin/products/product-create.html"
    form_class = ProductForm
    success_message = "محصول جدید با موفقیت افزوده شد"

    def form_valid(self, form):
        form.instance.user = self.request.user
        super().form_valid(form)
        return redirect(reverse_lazy("dashboard:admin:product-edit", kwargs={"pk": form.instance.pk}))

    def get_success_url(self):
        return reverse_lazy("dashboard:admin:product-list")


class AdminProductEditView(LoginRequiredMixin, HasAdminAccessPermission, SuccessMessageMixin, UpdateView):
    queryset = Product.objects.all()
    template_name = "dashboard/admin/products/product-edit.html"
    form_class = ProductForm
    success_message = "بروزرسانی محصول با موفقیت انجام شد."

    def get_success_url(self):
        return reverse_lazy("dashboard:admin:product-edit", kwargs={"pk": self.get_object().pk})


class AdminProductDeleteView(LoginRequiredMixin, HasAdminAccessPermission, SuccessMessageMixin, DeleteView):
    queryset = Product.objects.all()
    template_name = "dashboard/admin/products/product-delete.html"
    success_message = "محصول شما با موفقیت حذف گردید."
    success_url = reverse_lazy("dashboard:admin:product-list")

core/templates/dashboard/admin/products/product-create.html
{% extends "dashboard/admin/base.html" %}
{% load static %}
{% load humanize %}
{% block extra_css %}
<style>
    .small-primary-button {
        padding: 3px 10px;
        background-color: #007bff; 
        color: white; 
        border: none; 
        cursor: pointer; 
        font-size: 10px;
        border-radius: 5px; 
    }
    
    .small-primary-button:hover,
    .small-primary-button:focus {
        background-color: #0056b3;
    }
</style>
{% endblock extra_css %}
{% block header %}
<!-- Breadcrumb -->
<nav aria-label="breadcrumb">
  <ol class="breadcrumb breadcrumb-light mb-0">
    <li class="breadcrumb-item">حساب</li>
    <li class="breadcrumb-item">داشبورد ادمین</li>
    <li class="breadcrumb-item">محصولات</li>
    <li class="breadcrumb-item active" aria-current="page">افزودن محصول</li>
  </ol>
</nav>
<!-- End Breadcrumb -->
{% endblock header %}
{% block content %}
<!-- Card -->
<div class="card">
    <!-- Header -->
    <div class="card-header border-bottom">
      <h5 class="card-header-title">افزودن محصول</h5>
    </div>
    <!-- End Header -->

    <!-- Body -->
    <div class="card-body">
      <form action="." enctype="multipart/form-data" method="post">
        {% csrf_token %}
        <div class="row d-flex ">
          <div class="col-md-6 mb-3">
            <label>نام محصول</label>
            {{form.title}}
          </div>
          <div class="col-md-6 mb-3">
            <label>slug محصول - <button class="small-primary-button" type="button"
                onclick="generateSlug()">ساخت slug</button> </label>
            {{form.slug}}
          </div>
          <div class="col-md-6 mb-3">
            <label>دسته بندی</label>
            {{form.category}}
          </div>
          <div class="col-md-3 mb-3">
            <label>قیمت</label>
            {{form.price}}
          </div>
          <div class="col-md-3 mb-3">
            <label>درصد تخفیف</label>
            {{form.discount_percent}}
          </div>
          <div class="col-md-4 mb-3">
            <label>موجودی</label>
            {{form.stock}}
          </div>
          <div class="col-md-4 mb-3">
            <label>وضعیت نمایش</label>
            {{form.status}}
          </div>
          <div class="col-md-4 mb-3">
            <label>کد انبار</label>
            {{form.sku}}
          </div>
          <div class="col-md-12 mb-3">
            <label>توضیحات</label>
            {{form.description}}
            </div>
          </div>
          <div class="col-md-12 mb-3">
            <label>توضیحات کوتاه</label>
            {{form.short_description}}
            </div>
          </div>
          <div class="col-md-6 mb-3">
            <img id="img-preview" class="avatar avatar-xl avatar-4x3" src="/media/products/images.png" alt="">
          </div>
          <div class="col-md-6 mb-3">
            <label>تصویر</label>
            {{form.image}}
          </div>
        </div>
        <div class="card-footer">
            <div class=" d-flex pt-5 justify-content-end">
              <a class="btn btn-secondary ms-3" href="{% url "dashboard:admin:product-list" %}">بازگشت</a>
              <button type="submit" class="btn btn-primary ms-3">افزودن محصول</button>
            </div>
        </div>
      </form>
    </div>
</div>

<!-- End Body -->
{% endblock content %}
{% block extra_js %}
<script>
    function generateSlug() {
        const title = $("#id_title").val();
        const slug = slugify(title);
        $("#id_slug").val(slug)
    }
    function slugify(titleStr) {
        titleStr = titleStr.replace(/^\s+|\s+$/g, '');
        titleStr = titleStr.toLowerCase();
        //persian support
        titleStr = titleStr.replace(/[^a-z0-9_\s-ءاأإآؤئبتثجحخدذرزسشصضطظعغفقكلمنهويةى]#u/, '')
            // Collapse whitespace and replace by -
            .replace(/\s+/g, '-')
            // Collapse dashes
            .replace(/-+/g, '-');
        slugStr = titleStr;
        return slugStr;
    }
</script>
<script>
    document.addEventListener("DOMContentLoaded", function () {
      const imageInput = document.querySelector('input[name="image"]');
      const imagePreview = document.getElementById("img-preview");
  
      imageInput.addEventListener("change", function () {
        const file = this.files[0];
        if (file) {
          const reader = new FileReader();
  
          reader.onload = function (e) {
            imagePreview.src = e.target.result;
          };
  
          reader.readAsDataURL(file);
        } else {
          imagePreview.src = "";
        }
      });
    });
  </script>
{% endblock extra_js %}

core/templates/dashboard/admin/products/product-delete.html
{% extends "dashboard/admin/base.html" %}
{% load static %}
{% block header %}
<!-- Breadcrumb -->
<nav aria-label="breadcrumb">
  <ol class="breadcrumb breadcrumb-light mb-0">
    <li class="breadcrumb-item">حساب</li>
    <li class="breadcrumb-item">داشبورد ادمین</li>
    <li class="breadcrumb-item">محصولات</li>
    <li class="breadcrumb-item active" aria-current="page">حذف محصول</li>
  </ol>
</nav>
<!-- End Breadcrumb -->
{% endblock header %}
{% block content %}
<!-- Card -->
<div class="card">
    <!-- Header -->
    <div class="card-header border-bottom">
      <h5 class="card-header-title">حذف محصول</h5>
    </div>
    <!-- End Header -->

    <!-- Body -->
    <div class="card-body">
      <form action="." method="post">
        {% csrf_token %}
        <div class="row d-flex ">
          <p>آیا از حذف محصول زیر اطمینان دارید؟</p>
          <div class="row">
            <span>شناسه محصول: {{object.id}}</span>
            <span>نام محصول: {{object.title}}</span>
            <span>SKU محصول: {{object.sku}}</span>
          </div>
        </div>
        <div class="card-footer">
            <div class=" d-flex pt-5 justify-content-end">
              <button type="submit" class="btn btn-danger ms-3">تایید حذف</button>
              <a class="btn btn-secondary ms-3" href="{% url "dashboard:admin:product-edit" pk=object.pk%}">بازگشت</a>
            </div>
        </div>
      </form>
    </div>
</div>
<!-- End Body -->
{% endblock content %}

core/templates/dashboard/admin/products/product-edit.html
{% extends "dashboard/admin/base.html" %}
{% load static %}
{% load humanize %}
{% block extra_css %}
<style>
    .small-primary-button {
        padding: 3px 10px;
        background-color: #007bff; 
        color: white; 
        border: none; 
        cursor: pointer; 
        font-size: 10px;
        border-radius: 5px; 
    }
    
    .small-primary-button:hover,
    .small-primary-button:focus {
        background-color: #0056b3;
    }
</style>
{% endblock extra_css %}
{% block header %}
<!-- Breadcrumb -->
<nav aria-label="breadcrumb">
  <ol class="breadcrumb breadcrumb-light mb-0">
    <li class="breadcrumb-item">حساب</li>
    <li class="breadcrumb-item">داشبورد ادمین</li>
    <li class="breadcrumb-item">محصولات</li>
    <li class="breadcrumb-item active" aria-current="page">ویرایش محصول</li>
  </ol>
</nav>
<!-- End Breadcrumb -->
{% endblock header %}
{% block content %}
<!-- Card -->
<div class="card">
    <!-- Header -->
    <div class="card-header border-bottom">
      <h5 class="card-header-title">ویرایش/ساخت محصول</h5>
    </div>
    <!-- End Header -->

    <!-- Body -->
    <div class="card-body">
      <form action="." enctype="multipart/form-data" method="post">
        {% csrf_token %}
        <div class="row d-flex ">
          <div class="col-md-6 mb-3">
            <label>نام محصول</label>
            {{form.title}}
          </div>
          <div class="col-md-6 mb-3">
            <label>slug محصول - <button class="small-primary-button" type="button"
                onclick="generateSlug()">ساخت slug</button> </label>
            {{form.slug}}
          </div>
          <div class="col-md-6 mb-3">
            <label>دسته بندی</label>
            {{form.category}}
          </div>
          <div class="col-md-3 mb-3">
            <label>قیمت</label>
            {{form.price}}
          </div>
          <div class="col-md-3 mb-3">
            <label>درصد تخفیف</label>
            {{form.discount_percent}}
          </div>
          <div class="col-md-4 mb-3">
            <label>موجودی</label>
            {{form.stock}}
          </div>
          <div class="col-md-4 mb-3">
            <label>وضعیت نمایش</label>
            {{form.status}}
          </div>
          <div class="col-md-4 mb-3">
            <label>کد انبار</label>
            {{form.sku}}
          </div>
          <div class="col-md-12 mb-3">
            <label>توضیحات</label>
            {{form.description}}
            </div>
          </div>
          <div class="col-md-12 mb-3">
            <label>توضیحات کوتاه</label>
            {{form.short_description}}
            </div>
          </div>
          <div class="col-md-12 mb-3">
            <label>تصویر</label>
            {{form.image}}
          </div>
        </div>
        <div class="card-footer">
            <div class=" d-flex pt-5 justify-content-end">
              <a class="btn btn-danger ms-3">حذف</a>
              <a class="btn btn-secondary ms-3" href="{% url "dashboard:admin:product-list" %}">بازگشت</a>
              <button type="submit" class="btn btn-primary ms-3">ثبت تغییرات</button>
            </div>
        </div>
      </form>
    </div>
</div>

<!-- End Body -->
{% endblock content %}
{% block extra_js %}
<script>
    function generateSlug() {
        const title = $("#id_title").val();
        const slug = slugify(title);
        $("#id_slug").val(slug)
    }
    function slugify(titleStr) {
        titleStr = titleStr.replace(/^\s+|\s+$/g, '');
        titleStr = titleStr.toLowerCase();
        //persian support
        titleStr = titleStr.replace(/[^a-z0-9_\s-ءاأإآؤئبتثجحخدذرزسشصضطظعغفقكلمنهويةى]#u/, '')
            // Collapse whitespace and replace by -
            .replace(/\s+/g, '-')
            // Collapse dashes
            .replace(/-+/g, '-');
        slugStr = titleStr;
        return slugStr;
    }
</script>
{% endblock extra_js %}

core/templates/dashboard/admin/products/product-list.html
{% extends "dashboard/admin/base.html" %}
{% load static %}
{% load humanize %}
{% block header %}
<!-- Breadcrumb -->
<nav aria-label="breadcrumb">
  <ol class="breadcrumb breadcrumb-light mb-0">
    <li class="breadcrumb-item">حساب</li>
    <li class="breadcrumb-item">داشبورد ادمین</li>
    <li class="breadcrumb-item active" aria-current="page">لیست محصولات</li>
  </ol>
</nav>
<!-- End Breadcrumb -->
{% endblock header %}
{% block content %}
<!-- Card -->
<div class="card">
    <!-- Header -->
    <div class="card-header border-bottom">
      <div class="d-flex justify-content-between align-items-center">
        <h5 class="">لیست محصولات</h5>
        <a class="btn btn-primary" href="{% url "dashboard:admin:product-create" %}">افزودن محصول</a>
      </div>
    </div>
    <!-- End Header -->

    <!-- Body -->
    <div class="card-body">
      <div class="container pb-5">
        <form class="row">

          <!-- Input Card -->
          <div class="col-md-5 py-1">
            <input type="text" name="q" class="form-control" id="search-query-filter" placeholder="جستجوی" aria-label="جستجوی محصولات">
          </div>
          <!-- End Input Card -->
          <div class="col-md-3 py-1">
            <select class="form-select" id="order-by-filter">
                <option value="" selected>مرتب سازی</option>
                <option value="-created_at">جدیدترین</option>
                <option value="created_at">قدیمی ترین</option>
                <option value="-price">بیشترین قیمت</option>
                <option value="price">کمترین قیمت</option>
            </select>
          </div>
          <div class="col-md-3 py-1">
            <select class="form-select" name="category_id" id="category-id-filter">
                <option value="" selected>دسته بندی</option>
                {% for category in categories %}
                <option value="{{ category.id }}">{{ category.title }}</option>
                {% endfor %}
            </select>
          </div>
          <div class="col-md-1 py-1">
            <button type="submit" class="btn btn-primary btn-search"><i class="bi-search"></i></button>
          </div>
        </form>

      </div>

      <div class="row">
        <!-- Table -->
        <div class="table-responsive">
          <table class="table">
            <thead class="thead-light">
              <tr>
                <th scope="col">#</th>
                <th scope="col">تصویر</th>
                <th scope="col">نام</th>
                {% comment %} <th scope="col">دسته بندی</th> {% endcomment %}
                <th scope="col">قیمت</th>
                <th scope="col">تعداد</th>
                <th scope="col">وضعیت</th>
                <th scope="col">تخفیف</th>
                <th scope="col">عملیات</th>
              </tr>
            </thead>
            <tbody>
                {% for object in object_list  %}
                <tr>
                    <th scope="row">{{ forloop.counter0|add:page_obj.start_index }}</th>
                    <td class="align-content-center"><img class="avatar avatar-xl avatar-4x3" src="{{ object.image.url }}" alt="{{ object.title }}"/></td>
                    <td class="align-content-center">{{ object.title }}</td>
                    {% comment %} <td>کیف</td> {% endcomment %}
                    <td class="align-content-center">
                        {% if object.discount_percent %}
                        <del>{{ object.price|intcomma }}</del>
                        {{ object.get_price|intcomma  }}
                        {% else %}
                        {{ object.price|intcomma }}
                        {% endif %}
                    </td>
                    <td class="align-content-center">{{ object.stock }}</td>
                    <td class="align-content-center">
                        {% if object.status == 2 %}
                        <span class="badge bg-success">نشر شده</span>
                        {% else %}
                        <span class="badge bg-danger">عدم انتشار</span>
                        {% endif %}
                    </td>
                    <td class="align-content-center">%{{object.discount_percent}}</td>
                    <td class="align-content-center">
                      <a class="btn btn-sm btn-icon btn-ghost-secondary" href="{% url "dashboard:admin:product-edit" pk=object.pk %}"><i class="bi-pencil-square"></i></a>
                      <a class="btn btn-sm btn-icon btn-ghost-danger" href="{% url "dashboard:admin:product-delete" pk=object.pk %}"><i class="bi-trash"></i></a>
                      {% if object.status == 2 %}
                      <a class="btn btn-sm btn-icon btn-ghost-primary" target="_blank" href="{% url "shop:product-detail" slug=object.slug %}"><i class="bi-eye"></i></a>
                      {% endif %}
                    </td>
                </tr>
                {% empty %}
                <div class="row text-center w-100 py-5">
                    <p class="text-center">هیچ کالایی برای نمایش وجود ندارد</p>
                </div>
                <!-- End Col -->
                {% endfor %}
            </tbody>
          </table>
          <p>تعداد محصولات {{total_items}}</p>
        </div>
        <!-- End Table -->

        {% if page_obj.has_other_pages %}
        <!-- Pagination -->
        <div class="row pt-5 mt-3">
        <nav aria-label="Page navigation py-3">
            <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
            <li class="page-item">
                <button class="page-link" onclick="changePage({{ page_obj.previous_page_number }})">قبلی</button>
            </li>
            {% endif %}
            {% for page in page_obj.paginator %}
            {% if page.number == page_obj.number %}
            <li class="page-item active"><button class="page-link" onclick="changePage({{ page.number }})">{{ page.number }}</button></li>
            {% elif page.number > page_obj.number|add:'-3' and page.number < page_obj.number|add:'3' %}
            <li class="page-item"><button class="page-link" onclick="changePage({{ page.number }})">{{ page.number }}</button></li>
            {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
                <li class="page-item">
                    <button class="page-link" onclick="changePage({{ page_obj.next_page_number }})" aria-label="Next">بعدی</button>
                </li>
            {% endif %}
                </ul>
            </nav>
        </div>
        {% endif %}
      </div>
      <!-- End Row -->

    </div>
    <!-- End Body -->
</div>
<!-- End Card -->
{% endblock content %}
{% block extra_js %}
<script>
    $(document).ready(function(){
        let current_url_params = new URLSearchParams(window.location.search)
        $("#search-query-filter").val(current_url_params.get("q") || "")
        $("#order-by-filter").val(current_url_params.get("order_by") || "")
        $("#category-id-filter").val(current_url_params.get("category_id") || "")
    })
    $("#page-size-filter").change(function(){
        let current_url_params = new URLSearchParams(window.location.search)
        var selectedOption = $(this).val();
        current_url_params.set("page_size", selectedOption)
        let new_url = window.location.pathname + "?" + current_url_params.toString()
        window.location.href = new_url
    })
    $("#order-by-filter").change(function(){
        let current_url_params = new URLSearchParams(window.location.search)
        var selectedOption = $(this).val();
        current_url_params.set("order_by", selectedOption)
        let new_url = window.location.pathname + "?" + current_url_params.toString()
        window.location.href = new_url
    })
</script>
{% endblock extra_js %}