core/cart/urls.py
from django.urls import path
from . import views

app_name = "cart"

urlpatterns = [
    path('session/add-product/', views.SessionAddProductView.as_view(),
         name='session-add-product'),
    path('session/remove-product/', views.SessionRemoveProductView.as_view(),
         name='session-remove-product'),
    path('session/update-product-quantity/', views.SessionUpdateProductQuantityView.as_view(),
         name='session-update-product-quantity'),
    path('summary/', views.CartSummaryView.as_view(),
         name='cart-summary'),
]

core/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
    path('', include('website.urls')),
    path('accounts/', include('accounts.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('shop/', include('shop.urls')),
    path('cart/', include('cart.urls')),
    path('order/', include('order.urls')),
    path('payment/', include('payment.urls')),
    path('review/', include('review.urls')),
]


if settings.SHOW_DEBUGGER_TOOLBAR:
    urlpatterns += [path('__debug__/', include('debug_toolbar.urls')),
                    ]


if settings.DEBUG:
    # add root static files
    urlpatterns = urlpatterns + \
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    # add media static files
    urlpatterns = urlpatterns + \
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/shop/urls.py
from django.urls import path, re_path
from . import views

app_name = "shop"

urlpatterns = [
    path("product/grid/", views.ProductGridView.as_view(), name="product-grid"),
    re_path(r"product/(?P<slug>[^/]+)/",
            views.ProductDetailView.as_view(), name="product-detail"),
    path('add-or-remove-wishlist/', views.AddOrRemoveWishlistView.as_view(),
         name='add-or-remove-wishlist'),
]

core/templates/base/_footer_refrences.html
{% load static %}
<!-- JS Jquery-->
<script src="{% static 'js/jquery.min.js' %}"></script>

<!-- JS Implementing Plugins -->
<script src="{% static 'js/vendor.min.js' %}"></script>

<!-- JS Front -->
<script src="{% static 'js/theme.min.js' %}"></script>

<!-- JS Toastify -->
<script src="{% static 'vendor/toastify/toastify.js' %}"></script>

<!-- JS Custom -->
<script src="{% static 'js/custom.js' %}"></script>


<!-- JS Plugins Init. -->
<script>
  (function () {
    // INITIALIZATION OF MEGA MENU
    // =======================================================
    new HSMegaMenu('.js-mega-menu', {
      desktop: {
        position: 'left'
      }
    })


    // INITIALIZATION OF SHOW ANIMATIONS
    // =======================================================
    new HSShowAnimation('.js-animation-link')


    // INITIALIZATION OF BOOTSTRAP VALIDATION
    // =======================================================
    HSBsValidation.init('.js-validate', {
      onSubmit: data => {
        data.event.preventDefault()
        alert('Submited')
      }
    })


    // INITIALIZATION OF BOOTSTRAP DROPDOWN
    // =======================================================
    HSBsDropdown.init()


    // INITIALIZATION OF GO TO
    // =======================================================
    new HSGoTo('.js-go-to')


    // INITIALIZATION OF SWIPER
    // =======================================================
    var sliderThumbs = new Swiper('.js-swiper-shop-hero-thumbs', {
      watchSlidesVisibility: true,
      watchSlidesProgress: true,
      history: false,
      slidesPerView: 3,
      spaceBetween: 15,
      on: {
        beforeInit: (swiper) => {
          const css = `.swiper-slide-thumb-active .swiper-thumb-progress .swiper-thumb-progress-path {
                opacity: 1;
                -webkit-animation: ${swiper.originalParams.autoplay.delay}ms linear 0ms forwards swiperThumbProgressDash;
                animation: ${swiper.originalParams.autoplay.delay}ms linear 0ms forwards swiperThumbProgressDash;
            }`
          style = document.createElement('style')
          document.head.appendChild(style)
          style.type = 'text/css'
          style.appendChild(document.createTextNode(css));

          swiper.el.querySelectorAll('.js-swiper-thumb-progress')
            .forEach(slide => {
              slide.insertAdjacentHTML('beforeend', '<span class="swiper-thumb-progress"><svg version="1.1" viewBox="0 0 160 160"><path class="swiper-thumb-progress-path" d="M 79.98452083651917 4.000001576345426 A 76 76 0 1 1 79.89443752470656 4.0000733121155605 Z"></path></svg></span>')
            })
        },
      },
    });

    var swiper = new Swiper('.js-swiper-shop-classic-hero', {
      autoplay: true,
      loop: true,
      navigation: {
        nextEl: '.js-swiper-shop-classic-hero-button-next',
        prevEl: '.js-swiper-shop-classic-hero-button-prev',
      },
      thumbs: {
        swiper: sliderThumbs
      }
    });


    // INITIALIZATION OF COUNTDOWN
    // =======================================================
    const oneYearFromNow = new Date()

    document.querySelectorAll('.js-countdown').forEach(item => {
      const days = item.querySelector('.js-cd-days'),
        hours = item.querySelector('.js-cd-hours'),
        minutes = item.querySelector('.js-cd-minutes'),
        seconds = item.querySelector('.js-cd-seconds')

      countdown(oneYearFromNow.setFullYear(
        oneYearFromNow.getFullYear() + 1),
        ts => {
          days.innerHTML = ts.days
          hours.innerHTML = ts.hours
          minutes.innerHTML = ts.minutes
          seconds.innerHTML = ts.seconds
        },
        countdown.DAYS | countdown.HOURS | countdown.MINUTES | countdown.SECONDS
      )
    })
  })()
</script>
<script>
  function addToCart(product_id) {
      // console.log(product_id);
      $.ajax({
          url: '{% url "cart:session-add-product" %}',
          method: 'POST',
          data: {
              product_id: product_id,
              csrfmiddlewaretoken: '{{ csrf_token }}'
          },
          success: function (response) {
              if (!response.error) {
                  // Update the total cart item count dynamically
                  $("#total-cart-item-count").html(response.total_quantity);

                  // Display success messages
                  if (response.messages) {
                      response.messages.forEach(function(message) {
                          Toastify({
                              text: message,
                              className: "success",
                              style: {
                                  background: "blue"
                              }
                          }).showToast();
                      });
                  }
              }
          },
          error: function (jqXHR) {
              let response = jqXHR.responseJSON;
              if (response && response.messages) {
                  // Display error messages
                  response.messages.forEach(function(message) {
                      Toastify({
                          text: message,
                          className: "error",
                          style: {
                              background: "red"
                          }
                      }).showToast();
                  });
              }
          }
      });
  }
function addToWishlist(product_id) {
    $.ajax({
        url: '{% url "shop:add-or-remove-wishlist" %}', // URL for the AddToWishlistView
        method: 'POST',
        data: {
            product_id: product_id,
            csrfmiddlewaretoken: '{{ csrf_token }}'
        },
        success: function (response) {
          Toastify({
            text: response.message,
            className: "success",
            style: {
                background: "blue"
              }
            }).showToast();

            $(`i[data-product-id="${product_id}"]`).toggleClass('text-danger');
        },
        error: function (jqXHR, textStatus, errorThrown) {
            console.log(errorThrown);
        }
    });
}
</script>

core/templates/base/_header_refrences.html
{% load static %}
<!-- Font -->
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600&display=swap" rel="stylesheet">
<!-- CSS Implementing Plugins -->
<link rel="stylesheet" href="{% static 'css/vendor.min.css' %}">
<link rel="stylesheet" href="{% static 'vendor/bootstrap-icons/font/bootstrap-icons.css' %}">
<!-- CSS Front Template -->
<link rel="stylesheet" href="{% static 'css/theme.min.css' %}">
<link rel="stylesheet" href="{% static 'css/custom.css' %}">
<!-- CSS Toastify -->
<link rel="stylesheet" href="{% static 'vendor/toastify/toastify.css' %}">

core/templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="fa" dir="rtl">
  <head>
    <!-- Required Meta Tags Always Come First -->
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <!-- Title -->
    <title>
      {% block title %}فروشگاه | جلو - قالب چند منظوره پاسخگو{% endblock title%}
    </title>
    {% include "base/_header_refrences.html" %} 
    {% block extra_css %}{% endblock extra_css %} 
    {% block extra_css_no_compress %}{% endblock extra_css_no_compress %}
    <!-- Favicon -->
    <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}" />
  </head>
  <body>
    {% include "base/shared/header.html" %}
    <!-- ========== MAIN CONTENT ========== -->
    <main id="content" role="main">{% block content %}{% endblock content %}</main>
    <!-- ========== END MAIN CONTENT ========== -->
    {% include "base/shared/footer.html" %}
    {% include "base/_footer_refrences.html" %} 
    {% include "messages.html" %} 
    {% block extra_js %} {% endblock extra_js %} 
    {% block extra_js_no_compress %} {% endblock extra_js_no_compress %}
  </body>
</html>