core/cart/urls.py
from django.urls import path
from . import views

app_name = "cart"

urlpatterns = [
    path('session/add-product/', views.SessionAddProductView.as_view(),
         name='session-add-product'),
    path('session/remove-product/', views.SessionRemoveProductView.as_view(),
         name='session-remove-product'),
    path('session/update-product-quantity/', views.SessionUpdateProductQuantityView.as_view(),
         name='session-update-product-quantity'),
    path('summary/', views.CartSummaryView.as_view(),
         name='cart-summary'),
]

core/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
    path('', include('website.urls')),
    path('accounts/', include('accounts.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('shop/', include('shop.urls')),
    path('cart/', include('cart.urls')),
    path('order/', include('order.urls')),
    path('payment/', include('payment.urls')),
    path('review/', include('review.urls')),
]


if settings.SHOW_DEBUGGER_TOOLBAR:
    urlpatterns += [path('__debug__/', include('debug_toolbar.urls')),
                    ]


if settings.DEBUG:
    # add root static files
    urlpatterns = urlpatterns + \
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    # add media static files
    urlpatterns = urlpatterns + \
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/order/urls.py
from django.urls import path
from . import views

app_name = "order"

urlpatterns = [
    path("validate-coupon/", views.OrderValidateCouponView.as_view(),
         name="validate-coupon"),
    path("checkout/", views.OrderCheckOutView.as_view(), name="checkout"),
    path("completed/", views.OrderCompletedView.as_view(), name="completed"),
    path("failed/", views.OrderFailedView.as_view(), name="failed"),
]

core/shop/urls.py
from django.urls import path, re_path
from . import views

app_name = "shop"

urlpatterns = [
    path("product/grid/", views.ProductGridView.as_view(), name="product-grid"),
    re_path(r"product/(?P<slug>[^/]+)/",
            views.ProductDetailView.as_view(), name="product-detail"),
    path('add-or-remove-wishlist/', views.AddOrRemoveWishlistView.as_view(),
         name='add-or-remove-wishlist'),
]

core/dashboard/admin/forms/orders.py
from django import forms
from django.utils.translation import gettext_lazy as _
from order.models import Order


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = [
            'status',
            'payment',
        ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['status'].widget.attrs['class'] = "form-select"
        self.fields['payment'].widget.attrs['class'] = "form-control"

core/order/forms.py
from django import forms
from .models import UserAddress, Coupon
from django.utils import timezone


class CheckOutForm(forms.Form):
    address_id = forms.IntegerField(required=True)
    coupon = forms.CharField(required=False)

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super(CheckOutForm, self).__init__(*args, **kwargs)

    def clean_address_id(self):
        address_id = self.cleaned_data.get('address_id')

        user = self.request.user
        try:
            address = UserAddress.objects.get(id=address_id, user=user)
        except UserAddress.DoesNotExist:
            raise forms.ValidationError(
                "Invalid address for the requested user.")

        return address

    def clean_coupon(self):
        code = self.cleaned_data.get('coupon')

        if not code:
            return None

        user = self.request.user
        coupon = None

        try:
            coupon = Coupon.objects.get(code=code)
        except Coupon.DoesNotExist:
            raise forms.ValidationError("کد تخفیف معتبر نمی باشد!")

        if coupon:
            if coupon.used_by.count() >= coupon.max_limit_usage:
                raise forms.ValidationError("خطای محدودیت در تعداد استفاده")

            if coupon.expiration_date and coupon.expiration_date < timezone.now():
                raise forms.ValidationError("کد تخفیف منقضی شده است")

            if user in coupon.used_by.all():
                raise forms.ValidationError(
                    "این کد تخفیف قبلا توسط شما استفاده شده است.")

        return coupon

core/dashboard/admin/views/orders.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import UpdateView, ListView, DetailView
from dashboard.admin.forms import OrderForm
from dashboard.permissions import HasAdminAccessPermission
from django.contrib.messages.views import SuccessMessageMixin
from order.models import Order, OrderStatus
from django.core import exceptions
from django.utils.translation import gettext_lazy as _
from order.utils import calculate_tax, calculate_shipping
from decimal import Decimal


class AdminOrderListView(LoginRequiredMixin, HasAdminAccessPermission, ListView):
    template_name = "dashboard/admin/orders/order-list.html"
    paginate_by = 10

    def get_paginate_by(self, queryset):
        return self.request.GET.get('page_size', self.paginate_by)

    def get_queryset(self):
        queryset = Order.objects.prefetch_related('user').all()
        if search_q := self.request.GET.get("q"):
            queryset = queryset.filter(id__icontains=search_q)
        if status := self.request.GET.get("status"):
            queryset = queryset.filter(status=status)
        if order_by := self.request.GET.get("order_by"):
            try:
                queryset = queryset.order_by(order_by)
            except exceptions.FieldError:
                pass
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['total_items'] = self.get_queryset().count()
        context['statuses'] = OrderStatus.choices

        return context


class AdminOrderEditView(LoginRequiredMixin, HasAdminAccessPermission, SuccessMessageMixin, UpdateView):
    queryset = Order.objects.all()
    template_name = "dashboard/admin/orders/order-edit.html"
    form_class = OrderForm
    success_message = "بروزرسانی سفارش با موفقیت انجام شد."

    def get_success_url(self):
        return reverse_lazy("dashboard:admin:order-edit", kwargs={"pk": self.get_object().pk})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        order = self.object

        total_price = sum(
            item.price * item.quantity for item in order.order_items.all())

        # Apply coupon discount if available
        discount_amount = 0
        if order.coupon_at_order:
            discount_amount = round(
                total_price * Decimal(order.coupon_at_order) / 100)
            total_price -= discount_amount

        context['discount_amount'] = discount_amount

        return context


class AdminOrderInvoiceView(LoginRequiredMixin, HasAdminAccessPermission, DetailView):
    template_name = "dashboard/customer/orders/order-invoice.html"

    def get_queryset(self):
        return Order.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        order = self.object
        coupon = order.coupon

        total_price = sum(
            item.price * item.quantity for item in order.order_items.all())

        # Apply coupon discount if available
        discount_amount = 0
        if order.coupon_at_order:
            discount_amount = round(
                total_price * Decimal(order.coupon_at_order) / 100)
            total_price -= discount_amount

        total_tax = calculate_tax(total_price)
        shipping_cost = calculate_shipping(total_price)

        context['discount_amount'] = discount_amount
        context['discount_percent'] = order.coupon_at_order
        context['coupon'] = coupon
        context['shipping_cost'] = shipping_cost
        context['total_tax'] = total_tax

        return context

core/dashboard/customer/views/orders.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, DetailView
from dashboard.permissions import HasCustomerAccessPermission
from django.core import exceptions
from order.models import Order, OrderStatus
from order.utils import calculate_tax, calculate_shipping
from decimal import Decimal


class CustomerOrdersListView(LoginRequiredMixin, HasCustomerAccessPermission, ListView):
    template_name = "dashboard/customer/orders/order-list.html"
    paginate_by = 10

    def get_paginate_by(self, queryset):
        return self.request.GET.get('page_size', self.paginate_by)

    def get_queryset(self):
        queryset = Order.objects.prefetch_related(
            'order_items__product').filter(user=self.request.user)
        if search_q := self.request.GET.get("q"):
            queryset = queryset.filter(id__icontains=search_q)

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['total_orders'] = self.get_queryset().count()
        return context


class CustomerOrderDetailView(LoginRequiredMixin, HasCustomerAccessPermission, DetailView):
    template_name = "dashboard/customer/orders/order-detail.html"

    def get_queryset(self):
        return Order.objects.filter(user=self.request.user)


class CustomerOrderInvoiceView(LoginRequiredMixin, HasCustomerAccessPermission, DetailView):
    template_name = "dashboard/customer/orders/order-invoice.html"

    def get_queryset(self):
        return Order.objects.filter(status=OrderStatus.deliverd.value).filter(user=self.request.user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        order = self.object
        coupon = order.coupon

        total_price = sum(
            item.price * item.quantity for item in order.order_items.all())

        # Apply coupon discount if available
        discount_amount = 0
        if order.coupon_at_order:
            discount_amount = round(
                total_price * Decimal(order.coupon_at_order) / 100)
            total_price -= discount_amount

        total_tax = calculate_tax(total_price)
        shipping_cost = calculate_shipping(total_price)

        context['discount_amount'] = discount_amount
        context['discount_percent'] = order.coupon_at_order
        context['coupon'] = coupon
        context['shipping_cost'] = shipping_cost
        context['total_tax'] = total_tax

        return context

core/order/views.py
from django.shortcuts import render
from django.views.generic import FormView, TemplateView, View
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import UserAddress, Order, OrderItem, Coupon
from .forms import CheckOutForm
from cart.models import Cart
from cart.cart import CartSession
from .utils import calculate_tax, calculate_shipping
from django.urls import reverse_lazy
from django.shortcuts import redirect
from decimal import Decimal
from django.http import JsonResponse
from django.utils import timezone
from payment.models import Payment
from payment.zarinpal_client import ZarinPalSandBox
from django.contrib import messages


class OrderCheckOutView(LoginRequiredMixin, FormView):
    template_name = "order/checkout.html"
    form_class = CheckOutForm
    success_url = reverse_lazy("order:completed")

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['request'] = self.request
        return kwargs

    def form_valid(self, form):
        user = self.request.user
        cleaned_data = form.cleaned_data
        address = cleaned_data['address_id']
        coupon = cleaned_data['coupon']

        cart = Cart.objects.get(user=user)
        order = self.create_order(address, coupon)

        self.create_order_items(order, cart)
        self.clear_cart(cart)
        total_price = order.calculate_total_price()
        self.apply_coupon(coupon, order, user, total_price)
        order.save()

        return redirect(self.create_payment_url(order))

    def create_payment_url(self, order):
        zarinpal = ZarinPalSandBox()
        response = zarinpal.payment_request(round(order.total_price))
        data = response.get("data", {})
        authority = data.get("authority")
        if authority:
            payment_obj = Payment.objects.create(
                authority_id=authority,
                amount=round(order.total_price),
            )
            order.payment = payment_obj
            order.save()
            return zarinpal.generate_payment_url(authority)
        else:
            error_message = response.get("errors", {}).get(
                "message", "خطای ناشناخته")
            print(f"خطای درگاه زرین پال: {error_message}")
            messages.error(
                self.request, "پرداخت با خطا مواجه شد. لطفا مجدد تلاش کنید.")
            return redirect("order:checkout")

    def create_order(self, address, coupon):
        if coupon:
            return Order.objects.create(
                user=self.request.user,
                address=address.address,
                state=address.state,
                city=address.city,
                zip_code=address.zip_code,
                coupon_at_order=coupon.discount_percent,
            )
        else:
            return Order.objects.create(
                user=self.request.user,
                address=address.address,
                state=address.state,
                city=address.city,
                zip_code=address.zip_code,
            )

    def create_order_items(self, order, cart):
        for item in cart.cart_items.all():
            product = item.product

            OrderItem.objects.create(
                order=order,
                product=product,
                quantity=item.quantity,
                price=product.get_price(),
            )

        return False

    def clear_cart(self, cart):
        cart.cart_items.all().delete()
        CartSession(self.request.session).clear()

    def apply_coupon(self, coupon, order, user, total_price):
        if coupon:
            discount_amount = round(
                (total_price * Decimal(coupon.discount_percent / 100)))
            total_price -= discount_amount

            order.coupon = coupon
            coupon.used_by.add(user)
            coupon.save()

        total_tax = calculate_tax(total_price)
        total_price = total_price + total_tax
        shipping_cost = calculate_shipping(total_price)
        total_price += shipping_cost

        order.total_price = total_price

    def form_invalid(self, form):
        print(self.request.POST)
        return super().form_invalid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        try:
            cart = Cart.objects.get(user=self.request.user)
        except Cart.DoesNotExist:
            context['error'] = "کارت پیدا نشد."
            return context

        context['addresses'] = UserAddress.objects.filter(
            user=self.request.user
        )

        total_price = cart.calculate_total_price()
        total_tax = calculate_tax(total_price)
        total_price += total_tax
        shipping_cost = calculate_shipping(total_price)

        context['shipping_cost'] = shipping_cost
        context['total_tax'] = total_tax
        context['total_price'] = total_price + shipping_cost
        return context


class OrderCompletedView(LoginRequiredMixin, TemplateView):
    template_name = "order/completed.html"


class OrderFailedView(LoginRequiredMixin, TemplateView):
    template_name = "order/failed.html"


class OrderValidateCouponView(LoginRequiredMixin, View):

    def post(self, request, *args, **kwargs):
        code = request.POST.get("code")
        user = self.request.user

        status_code = 200
        message = "کد تخفیف با موفقیت ثبت شد."

        try:
            coupon = Coupon.objects.get(code=code)
        except Coupon.DoesNotExist:
            return JsonResponse({"message": "کد تخفیف معتبر نمی باشد."}, status=404)

        else:
            if coupon.used_by.count() >= coupon.max_limit_usage:
                status_code, message = 403, "خطای محدودیت در تعداد استفاده"

            elif coupon.expiration_date and coupon.expiration_date < timezone.now():
                status_code, message = 403, "کد تخفیف منقضی شده است"

            elif user in coupon.used_by.all():
                status_code, message = 403, "این کد تخفیف قبلا توسط شما استفاده شده است."

            else:
                cart = Cart.objects.get(user=self.request.user)
                total_price = cart.calculate_total_price()
                total_price = total_price - \
                    round(total_price * (coupon.discount_percent / 100))
                total_tax = calculate_tax(total_price)
                total_price += total_tax
                shipping_cost = calculate_shipping(total_price)
                total_price += shipping_cost
                if shipping_cost == 0:
                    shipping_cost = "رایگان"

        return JsonResponse({
            "message": message,
            "shipping_cost": shipping_cost,
            "total_tax": total_tax,
            "total_price": total_price
        }, status=status_code)

core/templates/order/checkout.html
{% extends "base/base.html" %}
{% load static %}
{% load humanize %}
{% block title %}فروشگاه | تسویه حساب{% endblock title%}
{% block content %}
<!-- Content -->
<div class="container content-space-1 content-space-lg-2">
    <div class="row">
      <div class="col-lg-8 mb-7 mb-lg-0">
        <h4 class="mb-3">انتخاب آدرس</h4>
        <!-- Form -->
        <form action="." method="post" id="checkout-form">
          {% csrf_token %}
          <hr class="my-4">

          <div class="d-grid gap-2">

            <!-- Check -->
             {% for address in addresses %}
              <div class="form-check">
                <h4 class="form-check-label mt-2">{{address.title}}</h4>
                <input type="radio" class="form-check-input" name="address_id" value="{{address.id}}" required>
                <label class="form-check-label" for="address">{{address.state}}, {{address.city}}, {{address.address}}</label>
                <p class="form-check-label mt-2">کد پستی: {{ address.zip_code }}</p>
              </div>
             {% endfor %}
            <!-- End Check -->
            <div>
              <a class="" href="{% url "dashboard:customer:address-list" %}">مدیریت آدرس ها</a>
            </div>
          </div>

          <hr class="my-4">

          <h4 class="mb-3">روش پرداخت</h4>

          <div class="my-3">
            <!-- Check -->
            <div class="form-check">
              <input id="creditShopCheckout" name="paymentMethod" type="radio" class="form-check-input" checked
                required>
              <label class="form-check-label" for="creditShopCheckout">پرداخت آنلاین</label>
            </div>
            <!-- End Check -->

            <!-- Check -->
            <div class="form-check">
              <input id="debitShopCheckout" name="paymentMethod" type="radio" class="form-check-input" required>
              <label class="form-check-label" for="debitShopCheckout">کارت به کارت</label>
            </div>
            <!-- End Check -->
          </div>


          <hr class="my-4">

          <div class="row align-items-center">



            <div class="col-sm text-center text-sm-start">
              <a class="link" href="{% url "cart:cart-summary" %}">
                بازگشت به سبد خرید <i class="bi-chevron-left small ms-1"></i> 
              </a>
            </div>
            <!-- End Col -->
          </div>
          <!-- End Row -->
        </form>
        <!-- End Form -->
      </div>
      <!-- End Col -->

      <div class="col-lg-4">
        <div class="ps-lg-4">
          <!-- Card -->
          <div class="card card-sm shadow-sm mb-4">
            <div class="card-body">
              <div class="border-bottom pb-4 mb-4">
                <h3 class="card-header-title">خلاصه سفارش</h3>
              </div>

                <div class="input-group border-bottom pb-4 mb-3 ">
                  <input type="text" class="form-control text-center" name="coupon" placeholder="کد تخفیف"
                  aria-label="کد تخفیف" form="checkout-form" id="coupon-input">
                  <button class="btn btn-primary" type="button" onclick="validateCoupon()"> بررسی</button>
                </div>

                <div class="border-bottom pb-4 mb-4">
                  <div class="d-grid gap-3">

                    <!-- End Row -->

                    <dl class="row">
                      <dt class="col-sm-6">هزینه ارسال</dt>
                      {% if shipping_cost %}
                      <dd class="col-sm-12 text-sm-end mb-0" id="shipping-cost">{{shipping_cost|intcomma}} تومان</dd>
                      {% else %}
                      <dd class="col-sm-12 text-sm-end mb-0" id="shipping-cost">رایگان</dd>
                      {% endif %}
                    </dl>
                    <!-- End Row -->
                  </div>
                </div>

                <div class="d-grid gap-3 mb-4">
                  <dl class="row">
                    <dt class="col-sm-6">مالیات</dt>
                    <dd class="col-sm-12 text-sm-end mb-0" id="total-tax">{{ total_tax|intcomma }} تومان</dd>

                  </dl>
                  <!-- End Row -->

                  <dl class="row">
                    <dt class="col-sm-6">جمع کل</dt>
                    <dd class="col-sm-6 text-sm-end mb-0" id="total-price">{{ total_price|intcomma }} تومان</dd>
                  </dl>
                  <!-- End Row -->
                </div>

                <div class="d-grid">
                  <button type="submit" form="checkout-form" class="btn btn-primary btn-lg">ثبت نهایی</button>
                </div>
            </div>
            <!-- End Card -->
          </div>

          <!-- Media -->
          <div class="d-flex align-items-center">
            <div class="flex-shrink-0">
              <div class="svg-icon svg-icon-sm text-primary">
                <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                  <path fill-rule="evenodd" clip-rule="evenodd"
                    d="M22.1671 18.1421C22.4827 18.4577 23.0222 18.2331 23.0206 17.7868L23.0039 13.1053V5.52632C23.0039 4.13107 21.8729 3 20.4776 3H8.68815C7.2929 3 6.16183 4.13107 6.16183 5.52632V9H13C14.6568 9 16 10.3431 16 12V15.6316H19.6565L22.1671 18.1421Z"
                    fill="#035A4B" />
                  <path opacity="0.3" fill-rule="evenodd" clip-rule="evenodd"
                    d="M1.98508 18V13C1.98508 11.8954 2.88051 11 3.98508 11H11.9851C13.0896 11 13.9851 11.8954 13.9851 13V18C13.9851 19.1046 13.0896 20 11.9851 20H4.10081L2.85695 21.1905C2.53895 21.4949 2.01123 21.2695 2.01123 20.8293V18.3243C1.99402 18.2187 1.98508 18.1104 1.98508 18ZM5.99999 14.5C5.99999 14.2239 6.22385 14 6.49999 14H11.5C11.7761 14 12 14.2239 12 14.5C12 14.7761 11.7761 15 11.5 15H6.49999C6.22385 15 5.99999 14.7761 5.99999 14.5ZM9.49999 16C9.22385 16 8.99999 16.2239 8.99999 16.5C8.99999 16.7761 9.22385 17 9.49999 17H11.5C11.7761 17 12 16.7761 12 16.5C12 16.2239 11.7761 16 11.5 16H9.49999Z"
                    fill="#035A4B" />
                </svg>

              </div>
            </div>
            <div class="flex-grow-1 ms-2">
              <span class="small me-1">نیاز به پشتیبانی دارید؟</span>
              <a class="link small" href="#">ارسال تیکت</a>
            </div>
          </div>
          <!-- End Media -->
        </div>
      </div>
      <!-- End Col -->
    </div>
    <!-- End Row -->
</div>
<!-- End Content -->
{% endblock content %}
{% block extra_js %}
<script>
  function applyDiscount(total_price, total_tax, shipping_cost){
    $('#total-tax').html(total_tax)
    $('#shipping-cost').html(shipping_cost)
    $('#total-price').html(total_price)

    formatPriceInToman(document.getElementById("total-tax"))
    formatPriceInToman(document.getElementById("shipping-cost"))
    formatPriceInToman(document.getElementById("total-price"))
  }

  function validateCoupon(){
    $.ajax({
      url: '{% url "order:validate-coupon" %}',
      method: 'POST',
      data: {
          code: $('#coupon-input').val(),
          csrfmiddlewaretoken: '{{ csrf_token }}'
      },
      success: function (response) {
        console.log("success", response)
        Toastify({
          text: response.message,
          className: "info",
          style: {
            background: "blue",
          }
        }).showToast();
        applyDiscount(response.total_price, response.total_tax, response.shipping_cost)
      },
      error: function (jqXHR, textStatus, errorThrown) {
        console.log(errorThrown)
        const errorMessage = jqXHR.responseJSON && jqXHR.responseJSON.message
        ? jqXHR.responseJSON.message
        : "خطای ناشناخته‌ای رخ داده است.";
        Toastify({
          text:errorMessage,
          className: `error`,
          style: {
            background: "red",       // Red background
            color: "white",          // White text color
            fontWeight: "bold"       // Optional: Bold text
          }
        }).showToast();
      }
    });
  }
</script>
{% endblock extra_js %}

core/templates/order/completed.html
{% extends "base/base.html" %}
{% load static %}
{% load humanize %}
{% block title %}فروشگاه | دریافت سفارش {% endblock title%}
{% block content %}
<!-- Content -->
<div class="container content-space-2 content-space-lg-3">
    <div class="w-md-75 w-lg-50 text-center mx-md-auto">
        <div class="mb-5">
        <img class="img-fluid" src="{% static 'svg/illustrations/oc-hi-five.svg' %}" alt="Image Description" style="width: 15rem;">
        </div>

        <div class="mb-5">
        <h1 class="h2">سفارش شما تکمیل شد!</h1>
        <p>از سفارش شما متشکریم! سفارش شما در حال پردازش است و ظرف 3 تا 6 ساعت تکمیل خواهد شد. پس از تکمیل سفارش شما یک ایمیل تاییدیه دریافت خواهید کرد.</p>
        </div>

        <a class="btn btn-primary btn-transition rounded-pill px-6" href="{% url "shop:product-grid" %}">به خرید ادامه دهید</a>
    </div>
    </div>
    <!-- End Content -->
</div>
<!-- End Clients -->
{% endblock content %}

core/templates/order/failed.html
{% extends "base/base.html" %}
{% load static %}
{% load humanize %}
{% block title %}فروشگاه | خطای سفارش {% endblock title%}
{% block content %}
<!-- Content -->
<div class="container content-space-2 content-space-lg-3">
    <div class="w-md-75 w-lg-50 text-center mx-md-auto">
        <div class="mb-5">
        <img class="img-fluid" src="{% static 'svg/illustrations/oc-error.svg' %}" alt="Image Description" style="width: 15rem;">
        </div>

        <div class="mb-5">
        <h1 class="h2">پرداخت شما با خطا مواجه شد!</h1>
        <p>لطفا مجددا تلاش کنید</p>
        </div>

        <a class="btn btn-primary btn-transition rounded-pill px-6" href="{% url "shop:product-grid" %}">بازگشت به فروشگاه</a>
    </div>
    </div>
    <!-- End Content -->
</div>
<!-- End Clients -->
{% endblock content %}